env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:prettier/recommended"
  - "plugin:cypress/recommended"
parserOptions:
  ecmaVersion: 12
plugins:
  - "cypress"
rules:
    "no-trailing-spaces": "error",
    "indent": ["error", 2],
    "prefer-const": "error",
    "no-var": "error"
