name: Cypress tests

on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  run-cypress:
    name: Run Cyprecc tests
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
